### ISSUE TITLE
Website - Not Able to Tab to Individual Steps on the Main Step Page

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Ilab-do-good#69]
Keyboard only or screen reader users are not able to get to the links/icons that would take them to the individual step pages.

The icons should be focusable with a keyboard.

![complychain - main steps - poor color choice for the icons for those that are colorblind](https://user-images.githubusercontent.com/10423487/30120486-f9060b96-92f6-11e7-81c2-b076348c65d2.png)

**Comment by jfc3-dol** [comment]
I can now tab to the icons on the website but can barely see which one I'm on. 

In the iOS there is a solid black line around them as you tap on them. You can not get to the iOS icons by reading had t use my fingers to do so because I could see them and knew they were there.

For Android they have a thin blue line.

**Comment by JckICF** [comment]
Hi John,

I'm unsure on how to make the image map available on iOS.  I've tried what things I can find on the internet to solve the problem, but it doesn't seem to work.

As an alternate solution,  I've provided an offscreen ol containing all of the links labeled like the image areas are.  Would this work?

**Comment by jfc3-dol** [comment]
The current version OPA has on our DEV server can be activated with a keyboard for the different steps along with I can tap the steps on both of our iOS and Android devices.

If issues are not marked as having corrections made I'm not testing them which could be the reason this problem is open.

In the future, if you correct something, please explain the change in the issue, so I know it's been done.

I'm waiting for your response that you have removed an new code which might cause issues with the application before closing and I can also test one last time too.

**Comment by adriennerlong** [comment]
From ICF: A solution has been implemented.

**Comment by jfc3-dol** [comment]
VoiceOver now reads an unordered list of eight items below the Steps background. When doing so, it displays a solid black box around where the text will be. Once it gets to Steps 6 - 8 it makes the screen jump up and down for each remaining Step.

**Comment by jfc3-dol** [comment]
TalkBack now reads the list of eight items on the main Steps screen.

I'm removing the Android label and will check the web version when I get a chance.

**Comment by jfc3-dol** [comment]
JAWS now reads the list of eight items on the main Steps screen.

I'm removing the web label. Will close issue once the iOS issue is corrected.

**Comment by sanganalakshay** [comment]
The offscreen divs are moved far below the visible screen and there is no solid black box seen. Also there is no jumping of the screen when I checked on my device. 
But the "not able to tab to individual steps" issue still persists on iOS

**Comment by jfc3-dol** [comment]
@sanganalakshay,

Each time VoiceOver reads one of the Steps on iOS the screen blinked. The blinking happened on our  iPad Air 2 (10.3.3) when reading each Step. VoiceOver on our iPhone (10.3.3) had the same problem until we updated to 111.2.

So not sure what to do in case people can't upgrade past iOS version 10.

VoiceOver also read Step seven as "Review review".

**Comment by jfc3-dol** [comment]
VoiceOver is now reading Step 7 as "Step 7 Independent review" on both our devices.

Each time VoiceOver reads the different Steps our iPad Air 2 (10.3.3) blinks the screen. VoiceOver on our iPhone (111.2) does not have this issue. The flashing and blinking can be an issue for someone that uses a screen reader and also can have seizures caused by content blinking too quickly.
